In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
ufc=pd.read_csv("UFC DATASETS/UFC.csv")
event_details=pd.read_csv("UFC DATASETS/event_details.csv") 
fight_details=pd.read_csv("UFC DATASETS/fight_details.csv")
fighter_details=pd.read_csv("UFC DATASETS/fighter_details.csv")

In [3]:
ufc.shape,event_details.shape,fight_details.shape,fighter_details.shape

((8250, 124), (8250, 6), (8250, 86), (2598, 19))

## Initial Data Exploration

### UFC

In [4]:
ufc.head()

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,...,b_splm,b_str_acc,b_sapm,b_str_def,b_td_avg,b_td_avg_acc,b_td_def,b_sub_avg,winner,winner_id
0,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",36ec204f47e4d613,catch weight,0,Submission,1,275,...,3.11,48,3.08,50,5.82,45,40,0.7,Myktybek Orolbai,bf2c8e01b07d3eb1
1,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",a1afc16e21d1a807,lightweight,0,Decision - Unanimous,3,300,...,6.55,45,4.33,56,0.00,0,75,0.4,Rafael Fiziev,c814b4c899793af6
2,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",7513a00037094075,lightweight,0,KO/TKO,2,257,...,4.13,38,5.28,52,0.00,0,83,0.0,Nazim Sadykhov,ff62013d2fce6d13
3,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",e512b80bbaea36c2,welterweight,0,Decision - Unanimous,3,300,...,3.50,48,2.24,60,1.70,44,55,0.0,Seokhyeon Ko,4a07b1988477502c
4,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",03bc32bdb5a33496,light heavyweight,0,Decision - Unanimous,5,300,...,3.79,40,4.24,49,0.00,0,58,0.1,Khalil Rountree Jr.,749f572d1d3161fb

In [5]:
ufc= ufc[["event_id",
"event_name",
"date",
"location",
"fight_id",
"division",
"title_fight",
"method",
"finish_round",
"match_time_sec",
"total_rounds",
]]

In [6]:
ufc.head()

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,total_rounds
0,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",36ec204f47e4d613,catch weight,0,Submission,1,275,3.0
1,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",a1afc16e21d1a807,lightweight,0,Decision - Unanimous,3,300,3.0
2,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",7513a00037094075,lightweight,0,KO/TKO,2,257,3.0
3,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",e512b80bbaea36c2,welterweight,0,Decision - Unanimous,3,300,3.0
4,400c7b43c86d27d3,UFC Fight Night: Hill vs. Rountree Jr.,2025/06/21,"Baku, Azerbaijan",03bc32bdb5a33496,light heavyweight,0,Decision - Unanimous,5,300,5.0

In [7]:
ufc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_id        8250 non-null   object
 1   event_name      8250 non-null   object
 2   date            8250 non-null   object
 3   location        8250 non-null   object
 4   fight_id        8250 non-null   object
 5   division        8250 non-null   object
 6   title_fight     8250 non-null   int64
 7   method          8250 non-null   object
 8   finish_round    8250 non-null   int64
 9   match_time_sec  8250 non-null   int64
 10  total_rounds    8219 non-null   float64
dtypes: float64(1), int64(3), object(7)
memory usage: 709.1+ KB

In [8]:
ufc.describe(include="all")

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,total_rounds
count,8250,8250,8250,8250,8250,8250,8250.000000,8250,8250.000000,8250.000000,8219.000000
unique,738,738,733,172,8250,103,NaN,10,NaN,NaN,NaN
top,a6a9ab5a824e8f66,UFC 2: No Way Out,2016/11/19,"Las Vegas, Nevada, USA",802c0e4e228996ac,lightweight,NaN,Decision - Unanimous,NaN,NaN,NaN
freq,15,15,25,2787,1,1380,NaN,2955,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,0.055152,NaN,2.353576,227.964727,3.135296
std,NaN,NaN,NaN,NaN,NaN,NaN,0.228290,NaN,1.016986,97.419347,0.650322
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,5.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,151.000000,3.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,3.000000,291.000000,3.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,3.000000,300.000000,3.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,5.000000,1080.000000,5.000000

### Event Details

In [9]:
event_details.head()

,event_id,fight_id,date,location,winner,winner_id
0,400c7b43c86d27d3,03bc32bdb5a33496,"June 21, 2025","Baku, Azerbaijan",Khalil Rountree Jr.,749f572d1d3161fb
1,400c7b43c86d27d3,a1afc16e21d1a807,"June 21, 2025","Baku, Azerbaijan",Rafael Fiziev,c814b4c899793af6
2,400c7b43c86d27d3,8e5744c664fec3e9,"June 21, 2025","Baku, Azerbaijan",Curtis Blaydes,fa6796c55d6c5440
3,400c7b43c86d27d3,36ec204f47e4d613,"June 21, 2025","Baku, Azerbaijan",Myktybek Orolbai,bf2c8e01b07d3eb1
4,400c7b43c86d27d3,7513a00037094075,"June 21, 2025","Baku, Azerbaijan",Nazim Sadykhov,ff62013d2fce6d13

In [10]:
event_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   event_id   8250 non-null   object
 1   fight_id   8250 non-null   object
 2   date       8250 non-null   object
 3   location   8250 non-null   object
 4   winner     8104 non-null   object
 5   winner_id  8104 non-null   object
dtypes: object(6)
memory usage: 386.8+ KB

In [11]:
event_details.describe(include="all")

,event_id,fight_id,date,location,winner,winner_id
count,8250,8250,8250,8250,8104,8104
unique,738,8250,733,172,1811,1812
top,a6a9ab5a824e8f66,802c0e4e228996ac,"November 19, 2016","Las Vegas, Nevada, USA",Jim Miller,d1941565abf50b16
freq,15,1,25,2787,27,27

### Fight Details

In [12]:
fight_details.head()

,event_name,event_id,fight_id,r_name,r_id,b_name,b_id,division,title_fight,method,...,b_clinch_acc,b_ground_landed,b_ground_atmpted,b_ground_acc,b_landed_head_per,b_landed_body_per,b_landed_leg_per,b_landed_dist_per,b_landed_clinch_per,b_landed_ground_per
0,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,36ec204f47e4d613,Tofiq Musayev,ae81a3ac7b260411,Myktybek Orolbai,bf2c8e01b07d3eb1,catch weight,0,Submission,...,NaN,1.0,3.0,33.0,100.0,0.0,0.0,50.0,0.0,50.0
1,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,a1afc16e21d1a807,Rafael Fiziev,c814b4c899793af6,Ignacio Bahamondes,e4a47b07044ddd72,lightweight,0,Decision - Unanimous,...,38.0,0.0,0.0,NaN,46.0,26.0,28.0,94.0,6.0,0.0
2,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,7513a00037094075,Nazim Sadykhov,ff62013d2fce6d13,Nikolas Motta,37f560436d745c18,lightweight,0,KO/TKO,...,55.0,0.0,0.0,NaN,69.0,24.0,6.0,81.0,18.0,0.0
3,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,e512b80bbaea36c2,Seokhyeon Ko,4a07b1988477502c,Oban Elliott,6b56e94a59b7b134,welterweight,0,Decision - Unanimous,...,100.0,0.0,0.0,NaN,20.0,60.0,20.0,90.0,10.0,0.0
4,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,03bc32bdb5a33496,Jamahal Hill,5444c5a201d3ee5a,Khalil Rountree Jr.,749f572d1d3161fb,light heavyweight,0,Decision - Unanimous,...,NaN,0.0,0.0,NaN,29.0,41.0,29.0,100.0,0.0,0.0

In [13]:
fight_details=fight_details[[
    "event_name", "event_id", "fight_id", "r_name", "r_id", 
    "b_name", "b_id", "division", "title_fight", "method", 
    "finish_round", "match_time_sec", "total_rounds"
]]

In [14]:
fight_details.head()

,event_name,event_id,fight_id,r_name,r_id,b_name,b_id,division,title_fight,method,finish_round,match_time_sec,total_rounds
0,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,36ec204f47e4d613,Tofiq Musayev,ae81a3ac7b260411,Myktybek Orolbai,bf2c8e01b07d3eb1,catch weight,0,Submission,1,275,3.0
1,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,a1afc16e21d1a807,Rafael Fiziev,c814b4c899793af6,Ignacio Bahamondes,e4a47b07044ddd72,lightweight,0,Decision - Unanimous,3,300,3.0
2,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,7513a00037094075,Nazim Sadykhov,ff62013d2fce6d13,Nikolas Motta,37f560436d745c18,lightweight,0,KO/TKO,2,257,3.0
3,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,e512b80bbaea36c2,Seokhyeon Ko,4a07b1988477502c,Oban Elliott,6b56e94a59b7b134,welterweight,0,Decision - Unanimous,3,300,3.0
4,UFC Fight Night: Hill vs. Rountree Jr.,400c7b43c86d27d3,03bc32bdb5a33496,Jamahal Hill,5444c5a201d3ee5a,Khalil Rountree Jr.,749f572d1d3161fb,light heavyweight,0,Decision - Unanimous,5,300,5.0

In [15]:
fight_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8250 entries, 0 to 8249
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_name      8250 non-null   object
 1   event_id        8250 non-null   object
 2   fight_id        8250 non-null   object
 3   r_name          8250 non-null   object
 4   r_id            8250 non-null   object
 5   b_name          8250 non-null   object
 6   b_id            8250 non-null   object
 7   division        8250 non-null   object
 8   title_fight     8250 non-null   int64
 9   method          8250 non-null   object
 10  finish_round    8250 non-null   int64
 11  match_time_sec  8250 non-null   int64
 12  total_rounds    8219 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 838.0+ KB

In [16]:
fight_details.describe()

       title_fight  finish_round  match_time_sec  total_rounds
count  8250.000000   8250.000000     8250.000000   8219.000000
mean      0.055152      2.353576      227.964727      3.135296
std       0.228290      1.016986       97.419347      0.650322
min       0.000000      1.000000        5.000000      1.000000
25%       0.000000      1.000000      151.000000      3.000000
50%       0.000000      3.000000      291.000000      3.000000
75%       0.000000      3.000000      300.000000      3.000000
max       1.000000      5.000000     1080.000000      5.000000

### Fighter Details

In [17]:
fighter_details.head()

,id,name,nick_name,wins,losses,draws,height,weight,reach,stance,dob,splm,str_acc,sapm,str_def,td_avg,td_avg_acc,td_def,sub_avg
0,74fefd43f073cd2f,Joe Pardo,NaN,4,6,0,185.42,95.25,NaN,Southpaw,NaN,0.00,0,0.00,0,0.00,0,0,0.0
1,8c1ca54b5089d199,Maheshate,NaN,10,4,0,182.88,70.31,180.34,Orthodox,"Dec 01, 1999",3.86,29,5.64,53,0.00,0,45,0.0
2,4234f0097c83fa62,Sijara Eubanks,SarJ,8,7,0,162.56,56.70,170.18,Orthodox,"Apr 27, 1985",4.30,43,3.43,57,1.90,44,66,0.3
3,1291edf2d566a71a,Julio Arce,NaN,19,6,0,170.18,65.77,177.80,Southpaw,"Oct 27, 1989",4.36,36,3.05,68,0.46,28,96,0.3
4,7a47e068f8017019,Val Woodburn,The Animal,7,2,0,172.72,77.11,187.96,Orthodox,"Aug 10, 1993",1.60,35,4.93,36,1.92,100,50,0.0

In [18]:
fighter_details=fighter_details[[
    "id", 
    "name", 
    "nick_name", 
    "wins", 
    "losses", 
    "draws", 
    "height", 
    "weight", 
    "reach", 
    "stance"
]]

In [19]:
fighter_details.head()

,id,name,nick_name,wins,losses,draws,height,weight,reach,stance
0,74fefd43f073cd2f,Joe Pardo,NaN,4,6,0,185.42,95.25,NaN,Southpaw
1,8c1ca54b5089d199,Maheshate,NaN,10,4,0,182.88,70.31,180.34,Orthodox
2,4234f0097c83fa62,Sijara Eubanks,SarJ,8,7,0,162.56,56.70,170.18,Orthodox
3,1291edf2d566a71a,Julio Arce,NaN,19,6,0,170.18,65.77,177.80,Southpaw
4,7a47e068f8017019,Val Woodburn,The Animal,7,2,0,172.72,77.11,187.96,Orthodox

In [20]:
fighter_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2598 entries, 0 to 2597
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         2598 non-null   object
 1   name       2598 non-null   object
 2   nick_name  1682 non-null   object
 3   wins       2598 non-null   int64
 4   losses     2598 non-null   int64
 5   draws      2598 non-null   int64
 6   height     2577 non-null   float64
 7   weight     2580 non-null   float64
 8   reach      1943 non-null   float64
 9   stance     2521 non-null   object
dtypes: float64(3), int64(3), object(4)
memory usage: 203.1+ KB

In [21]:
fighter_details.describe()

,wins,losses,draws,height,weight,reach
count,2598.000000,2598.000000,2598.000000,2577.000000,2580.000000,1943.000000
mean,14.499615,6.160123,0.253272,178.279022,76.569217,181.991065
std,9.736844,4.534444,0.786718,8.966628,17.926687,10.768292
min,0.000000,0.000000,0.000000,152.400000,52.160000,147.320000
25%,9.000000,3.000000,0.000000,172.720000,65.770000,175.260000
50%,13.000000,5.000000,0.000000,177.800000,70.310000,182.880000
75%,18.000000,8.000000,0.000000,185.420000,83.910000,190.500000
max,253.000000,53.000000,11.000000,210.820000,349.270000,213.360000

## Export Cleaned Datasets

In [23]:
ufc.to_csv("UFC DATASETS/ufc_cleaned.csv",index=False)
event_details.to_csv("UFC DATASETS/event_details_cleaned.csv",index=False)
fight_details.to_csv("UFC DATASETS/fight_details_cleaned.csv",index=False)
fighter_details.to_csv("UFC DATASETS/fighter_details_cleaned.csv",index=False)